version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres01
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=kojofosu
      - POSTGRES_USER=kojofosu
      - POSTGRES_DB=tutorialdb
    restart: unless-stopped
  # This is my rest api app*****************************************
#  myfirstapp:
#    image: myfirst:0.1
#    network_mode: bridge
#    container_name: myfirst
#    expose:
#      - 8080
#    ports:
#      - 8081:8080
#    volumes:
#      - /home/pramod/Desktop:/var/tmp
#    restart: unless-stopped
#volumes:
#  postgres-data: